project_id = "ndulrvfwcqyvutcviebk"

[functions.generate-questions]
verify_jwt = false

[functions.generate-referral-code]
verify_jwt = true

[functions.track-affiliate-click]
verify_jwt = false

[functions.import-schedule-pdf]
verify_jwt = true

[functions.translate-content]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.check-payment-methods]
verify_jwt = true

[functions.hydrate-sign-metadata]
verify_jwt = false

[functions.generate-flashcards]
verify_jwt = false

[functions.create-booking-payment]
verify_jwt = true

[functions.get-payment-methods]
verify_jwt = true

[functions.create-setup-intent]
verify_jwt = true

[functions.create-video-session]
verify_jwt = true